" Vim syntax file
" Language: C Additions
" Date: mer. juil. 17 23:54:10 CEST 2019
" Generated by vim_make_syntaxe_file
 
" --- Functions 
 
syn keyword cLibFunction c16rtomb
syn keyword cLibFunction c32rtomb
syn keyword cLibFunction mbrtoc16
syn keyword cLibFunction mbrtoc32
 
" --- Structures 
 
 
" --- Macros 
 
syn keyword cLibMacro _UCHAR_H
syn keyword cLibMacro __need_size_t
 
" --- Enums 
 
 
" --- Members 
 
 
" --- Variables 
 
 
