" Vim syntax file
" Language: C Additions
" Date: mer. juil. 17 23:54:09 CEST 2019
" Generated by vim_make_syntaxe_file
 
" --- Functions 
 
syn keyword cLibFunction __errno_location
 
" --- Structures 
 
 
" --- Macros 
 
syn keyword cLibMacro _ERRNO_H
syn keyword cLibMacro errno
 
" --- Enums 
 
 
" --- Members 
 
 
" --- Variables 
 
 
